import javax.swing.*;
import java.awt.*;

/**
 * Created by Cyan on 2016/12/2.
 */
public class MainFrame extends Frame {
    private JPanel ContentPanel;
    private JButton BookButton;
    private JButton MessageButton;
    private JButton TransButton;
    private JButton OnlineButton;
    private JButton RegisterButton;
    private JButton LoginButton;
    private JPanel UpPanel;
    private JPanel UpRightPanel;
    private JPanel UpLeftPanel;
    private JPanel CenterPanel;
    private JButton LastwordButton;
    private JButton NextwordButton;
    private JTextField SearchwordtextField;
    private JButton SearchButton;
    private JButton OnlinesearchButton;
    private JCheckBox checkBox1;
    private JCheckBox 百度词典CheckBox;
    private JCheckBox 必应词典CheckBox;
    private JLabel Blanklabel1;
    private JLabel BlankLabel2;
    private JPanel DownPanel;
    private JButton button4;

    private void createUIComponents() {
        // TODO: place custom component creation code here
        //$$$setupUI$$$();
        //
        ContentPanel = new JPanel();
        BookButton = new JButton();
        MessageButton = new JButton();
        TransButton = new JButton();
        OnlineButton = new JButton();
        RegisterButton = new JButton();
        LoginButton = new JButton();
        UpPanel = new JPanel();
        UpRightPanel = new JPanel();
        UpLeftPanel = new JPanel();

        CenterPanel = new JPanel();
        ImageIcon icon1 = new ImageIcon("icon/ArrowLeft.png");
        Image temp = icon1.getImage().getScaledInstance(10, 15, Image.SCALE_DEFAULT);
        icon1 = new ImageIcon(temp);
        LastwordButton = new JButton(icon1);
        ImageIcon icon2 = new ImageIcon("icon/ArrowRight.png");
        temp = icon2.getImage().getScaledInstance(10, 15, Image.SCALE_DEFAULT);
        icon2 = new ImageIcon(temp);
        NextwordButton = new JButton(icon2);


        SearchwordtextField = new JTextField();
        SearchButton = new JButton();
        button4 = new JButton();

        DownPanel = new JPanel();


    }


    public static void main(String[] args) {
        JFrame frame = new JFrame("My Online Dictionary");
        frame.setContentPane(new MainFrame().ContentPanel);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        ContentPanel = new JPanel();
        ContentPanel.setLayout(new BorderLayout(0, 0));
        ContentPanel.setEnabled(true);
        UpPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 40, 5));
        UpPanel.setBackground(new Color(-4270593));
        ContentPanel.add(UpPanel, BorderLayout.NORTH);
        UpLeftPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 5));
        UpLeftPanel.setBackground(new Color(-4270593));
        UpLeftPanel.setEnabled(false);
        UpPanel.add(UpLeftPanel);
        TransButton.setBackground(new Color(-4270593));
        TransButton.setEnabled(true);
        TransButton.setFont(new Font(TransButton.getFont().getName(), TransButton.getFont().getStyle(), 16));
        TransButton.setForeground(new Color(-16777216));
        TransButton.setHideActionText(false);
        TransButton.setText("翻译");
        UpLeftPanel.add(TransButton);
        BookButton.setBackground(new Color(-4270593));
        BookButton.setEnabled(true);
        BookButton.setFont(new Font(BookButton.getFont().getName(), BookButton.getFont().getStyle(), 16));
        BookButton.setHideActionText(false);
        BookButton.setText("单词本");
        UpLeftPanel.add(BookButton);
        MessageButton.setBackground(new Color(-4270593));
        MessageButton.setEnabled(true);
        MessageButton.setFont(new Font(MessageButton.getFont().getName(), MessageButton.getFont().getStyle(), 16));
        MessageButton.setForeground(new Color(-16777216));
        MessageButton.setHideActionText(false);
        MessageButton.setText("消息");
        UpLeftPanel.add(MessageButton);
        OnlineButton.setBackground(new Color(-4270593));
        OnlineButton.setFont(new Font(OnlineButton.getFont().getName(), OnlineButton.getFont().getStyle(), 16));
        OnlineButton.setText("用户");
        UpLeftPanel.add(OnlineButton);
        final JLabel label1 = new JLabel();
        label1.setText("                ");
        UpPanel.add(label1);
        UpRightPanel.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        UpRightPanel.setBackground(new Color(-4270593));
        UpPanel.add(UpRightPanel);
        LoginButton.setBackground(new Color(-4270593));
        LoginButton.setFont(new Font(LoginButton.getFont().getName(), LoginButton.getFont().getStyle(), 16));
        LoginButton.setText("登录");
        UpRightPanel.add(LoginButton);
        RegisterButton.setBackground(new Color(-4270593));
        RegisterButton.setFont(new Font(RegisterButton.getFont().getName(), RegisterButton.getFont().getStyle(), 16));
        RegisterButton.setHorizontalAlignment(2);
        RegisterButton.setHorizontalTextPosition(2);
        RegisterButton.setText("注册");
        RegisterButton.setVerticalAlignment(0);
        UpRightPanel.add(RegisterButton);
        CenterPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        ContentPanel.add(CenterPanel, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("                     ");
        CenterPanel.add(label2);
        LastwordButton.setBackground(new Color(-1513240));
        LastwordButton.setEnabled(true);
        LastwordButton.setHideActionText(false);
        LastwordButton.setText("");
        CenterPanel.add(LastwordButton);
        NextwordButton.setBackground(new Color(-1513240));
        NextwordButton.setEnabled(true);
        NextwordButton.setHideActionText(false);
        NextwordButton.setText("");
        CenterPanel.add(NextwordButton);
        SearchwordtextField.setColumns(20);
        SearchwordtextField.setEditable(true);
        SearchwordtextField.setText("");
        CenterPanel.add(SearchwordtextField);
        SearchButton.setText("翻译");
        CenterPanel.add(SearchButton);
        OnlinesearchButton = new JButton();
        OnlinesearchButton.setHideActionText(false);
        OnlinesearchButton.setText("网络");
        CenterPanel.add(OnlinesearchButton);
        final JLabel label3 = new JLabel();
        label3.setText("                            ");
        CenterPanel.add(label3);
        DownPanel.setLayout(new BorderLayout(0, 0));
        CenterPanel.add(DownPanel);
        final JLabel label4 = new JLabel();
        label4.setText("Label");
        DownPanel.add(label4, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ContentPanel;
    }
}
